services:
  _defaults:
    public: true
    autowire: true
    bind:
      $bundleConfig: '%huh_form_autocomplete%'

  HeimrichHannot\FormAutocompleteBundle\EventListener\:
    resource: '../../EventListener/*'

  HeimrichHannot\FormAutocompleteBundle\EventListener\AdjustFilterOptionsEventListener:
    tags:
      - { name: kernel.event_listener, event: huh.filter.event.adjust_filter_options_event, method: '__invoke' }