services:
  _defaults:
    public: true
    autowire: true
    bind:
      $bundleConfig: '%huh_form_autocomplete%'

  HeimrichHannot\FormAutocompleteBundle\EventListener\:
    resource: '../../EventListener/*'
